### PR TITLE
Add reverse function for manipulating strings

### PR DESCRIPTION
**Pull request by CristianCantoro**
This pull request adds a function `reverse` for manipulating strings that reverse a string.

Here's an example:
```
> cat text-reverse.txt
123
456
789
```

and with `reverse`:
```
> cat test-reverse.txt | map reverse
321
654
987
```

The name comes from Python's bultin method [`reversed()`](https://docs.python.org/3/library/functions.html#reversed), that reverses a sequence.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

Could the type annotation be generalized such that `reverse` can also be applied to arrays (see #7)?

**Comment by CristianCantoro** [comment]
@sharkdp wrote:
> Could the type annotation be generalized such that `reverse` can also be applied to arrays (see #7)?

I am not sure on how this should work, can you make an example on how it would work on an array input?

Thanks!

**Comment by sharkdp** [comment]
Arrays can be created by functions such as `split`, `duplicate` or `split_ext` (see also https://github.com/sharkdp/shell-functools#working-with-columns).

For example:
``` bash
> echo "11,12,13" | map split ","         
11	12	13
```

Calling `map reverse` on this should reverse the array:
```
▶ echo "1,2,3" | map split "," | map reverse
13	12	11
```

In order to do this, you would probably have to use
``` python
@typed(None, None)
```
See the `nonempty` function for an example. It also works on strings and arrays.

**Comment by CristianCantoro** [comment]
Hi,

I have changed the implementation so that the `reverse` function can handle arrays:

```
> cat test-reverse-array.txt
123,456,789
aaa,bbb,ccc
1,2,3

> cat test-reverse-array.txt | map split ','              
123	456	789
aaa	bbb	ccc
1	2	3

> cat test-reverse-array.txt | map split ',' | map reverse
789	456	123
ccc	bbb	aaa
3	2	1
```

I have also added some error handling:
```
> echo 10 | map gt 5
True

> echo 10 | map gt 5 | map reverse
[functools error] Cannot reverse bool value
```

**Comment by sharkdp** [comment]
Thank you very much!

**Pull request merged**
