### PR TITLE
Add filter: is_exec, testing if path is executable

### PR DESCRIPTION
**Pull request by dboyliao**
Example:
`ls | filter is_exec | xargs -I % ls -l %`

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

I would prefer `is_executable` as a name. What do you think?

**Comment by dboyliao** [comment]
Ok, `is_executable` seems to be more specific, though it requires more typing.
I'm good either way.

**Comment by sharkdp** [comment]
Ok. It'd be great if you could change it to `is_executable`.

**Comment by dboyliao** [comment]
Done.
Waiting for the CI.

**Comment by dboyliao** [comment]
Oh, I should also update the README.md
A moment plz.

**Comment by sharkdp** [comment]
Thank you!

**Pull request merged**
